# Generated by Django 5.1.4 on 2024-12-12 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the event.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the event.')),
                ('date', models.DateTimeField(help_text='Date and time of the event.')),
                ('location', models.CharField(help_text='Location of the event.', max_length=255)),
                ('organizer', models.ForeignKey(help_text='User who organizes the event.', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of registration.')),
                ('event', models.ForeignKey(help_text='The event for which the user is registering.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(help_text='The user registering for the event.', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
